packages:
  - apps/*
  - packages/*
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
allowBuilds:
  esbuild: true
  sharp: true
  msgpackr-extract: true
  workerd: true
  canvas: set this to true or false
catalog:
  zod: ^4.5.4
  typescript: ^6.0.3
  "@types/node": ^26.4.1
  varlock: 1.18.0
  lucide-react: ^1.41.0
  next-themes: ^0.4.6
  react: ^19.2.8
  react-dom: ^19.2.8
  sonner: ^2.0.8
  tailwindcss: ^4.3.3
  convex: ^1.45.0
  better-auth: 1.6.17
  "@convex-dev/better-auth": ^0.12.5
  "@convex-dev/agent": ^0.7.3
  "@convex-dev/ai-sdk-provider": ^0.2.1
  "@exalabs/convex-exa": 0.1.1
  "@convex-dev/workflow": ^0.4.8
  "@convex-dev/ai-budget": 1.0.0-rc.0
  "@convex-dev/rate-limiter": ^0.4.0
  convex-test: ^0.0.59
  "@edge-runtime/vm": ^5.0.0
  vitest: ^5.0.1
  unpdf: ^1.8.1
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.7
  ai: ^7.0.109
minimumReleaseAgeExclude:
  - "@ai-sdk/gateway@4.0.88"
  - "@convex-dev/ai-sdk-provider@0.2.1"
  - ai@7.0.109
  - '@convex-dev/ai-budget@1.0.0-rc.0'
